### ISSUE TITLE
[Feature] Reflect exit status instead of `Down` status 

### ISSUE THREAD

**Issue by MathisWellmann** [pvolok/mprocs#127] opened 2024-04-14 19:19 UTC
# Scenario
I'm basically using `mprocs` as a quick local "CI" system, defining all the checks I need to run.
It's a fantastic workflow and this tool is perfect for it in my opinion.

# Proposal
But I wish instead of showing `Down` in red, it would show more nuanced feedback.
For example a successfully executed command should display as `Finished` (or some other name) when the Exit code is 0.
This could show up  as a vibrant green (in a different shade compared to `Up`).

Any other exit code besides 0 could maybe be shown as `Exit(1)` in red.

# Benefits
It would make it much easier to identify the different states of processes without having to navigate to the process to focus it.

# Note
If this is something that people want, then I'm willing to create a PR for it.
Feedback would be appreciated.

**Comment by pvolok** [comment] 2024-04-21 20:15
Thank you for your feedback and proposal!

I agree that processes with exit code 0 should have different color. I suggest we keep the string "DOWN" as it is short and is the opposite of "UP". If you would like to make a PR that would be great. The code to render the "DOWN" label is here: https://github.com/pvolok/mprocs/blob/44000479034b7d35a862942c215b19c5b4109c83/src/ui_procs.rs#L75

Long term I would like to have some API for custom process statuses. For example, test runner would be able to indicate if it's currently running tests or show result. If you have any ideas or thoughts, please share.

**Comment by MathisWellmann** [comment] 2024-04-22 12:02
Sounds good.
I may find some time this week to create a PR :+1:

**Comment by legobeat** [comment] 2024-06-04 22:11
I just opened #134 with some thoughts - @MathisWellmann if you think it has enough overlap to be considered duplicate of this one let me know and I can close it, and move it here as a comment instead!

**Closed** 2024-07-26 17:25 UTC
