### ISSUE TITLE
Feature: Config option to automatically restart a process if stops running

### ISSUE THREAD

**Issue by mjsilva** [pvolok/mprocs#113] opened 2024-01-11 22:21 UTC
Firstly, thank you so much for building this!

I know this can be achieved outside mprocs easily but... I'm lazy :) It would be great if we could configure a process with `autorestart: true` and as soon as mprocs detects `DOWN` it would restart it.

Use case, I use mprocs to keep track of production logs like `gcloud beta run services logs tail production-cloud-run-service` and every-time I close my laptop or hit a gcloud stream limit it stops the process.

**Comment by ankush** [comment] 2024-03-22 14:02
Duplicate of https://github.com/pvolok/mprocs/issues/68

**Closed** 2024-04-06 19:19 UTC
