### ISSUE TITLE
YAML example global config yields errors

### ISSUE THREAD

**Issue by serhez** [pvolok/mprocs#31] opened 2022-06-16 13:02 UTC
Hello!

I'm trying to globally customise `mprocs` through `~/.config/mprocs/mprocs.yaml`. I started by using the example config you have in the README:

```
keymap_procs: # keymap when process list is focused
  <C-q>: { c: toggle-focus }
  <C-a>: null # unbind key
keymap_term: # keymap when terminal is focused
  reset: true
  <C-q>: { c: toggle-focus }
```

However, this yields the following error when trying to run `mprocs`:

```
Error: [global settings] invalid type: unit value, expected internally tagged enum AppEvent
```

I haven't worked with `rust` before, but I think it's coming from the `serde_yaml` library, triggered at `src/main.rs:68` <- `src/settings.rs:40` <- `src/settings.rs:86`.

**Comment by pvolok** [comment] 2022-06-17 02:32
The problem is in this line: `<C-a>: null`. I recently added unbinding keys, but didn't release the new version yet. I'll make a new release today or tomorrow. For now you can remove that like and it should work.

**Comment by serhez** [comment] 2022-06-17 14:40
Perfect, thanks!

**Comment by pvolok** [comment] 2022-06-17 15:49
Now this feature is released in mprocs 0.4.1.

**Closed by pvolok** 2022-06-17 15:49 UTC

**Comment by serhez** [comment] 2022-06-19 16:51
This was indeed resolved, thanks!
